# Generated by Django 2.0.2 on 2018-02-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollabMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['major', 'project'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['major'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('tagline', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(verbose_name='description')),
                ('created', models.DateTimeField(verbose_name='create_date')),
                ('fulfilled', models.BooleanField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('picture', models.ImageField(default='user_images/None/no-img.jpg', height_field='height', upload_to='user_images/', width_field='width')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
                ('logged_in', models.BooleanField()),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collabs.Major')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collabs.User'),
        ),
        migrations.AddField(
            model_name='collabmajor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.Major'),
        ),
        migrations.AddField(
            model_name='collabmajor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.Project'),
        ),
    ]
