# Generated by Django 2.0.2 on 2018-02-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabmajor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='collabmajor',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='major',
            old_name='major',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logged_in',
        ),
        migrations.AddField(
            model_name='project',
            name='collabMajors',
            field=models.ManyToManyField(to='collabs.Major'),
        ),
        migrations.AddField(
            model_name='project',
            name='collabUsers',
            field=models.ManyToManyField(blank=True, related_name='collaborators', related_query_name='collaborators', to='collabs.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CollabMajor',
        ),
    ]
