# Generated by Django 2.0.2 on 2018-02-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0002_auto_20180217_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('picture', models.ImageField(blank=True, default='user_images/None/no-img.jpg', height_field='height', upload_to='user_images/', width_field='width')),
                ('email', models.CharField(blank=True, max_length=32, verbose_name='email')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collabs.Major')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.AlterField(
            model_name='project',
            name='collabUsers',
            field=models.ManyToManyField(blank=True, related_name='collaborators', related_query_name='collaborators', to='collabs.Profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collabs.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
