# Generated by Django 2.0.2 on 2018-02-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0003_auto_20180217_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='user_images/None/no-img.jpg', upload_to='user_images/'),
        ),
    ]
